name: openx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  connectivity_plus: ^3.0.2
  get_storage: ^2.0.3
  nil: ^1.1.1
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  http: ^0.13.5
  fluentui_icons: ^1.0.0
  modal_bottom_sheet: ^2.1.2  
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/marketing/app-icon-1024.png"
  



flutter: 
  uses-material-design: true

  assets:
    - assets/app_icons/
    - assets/marketing/

